apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: mq-consumer-scaled-job
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 1200
    template:
      spec:
        containers:
        - name: mq-consumer
          image: autoscaleacr.azurecr.io/receive:latest
          name: mq-consumer
          resources:
            requests:
              cpu: 800m
              memory: 2048Mi
            limits:
              cpu: 800m
              memory: 2048Mi
          env:
          - name: hostname
            value: "rabbitmq.default.svc.cluster.local"
          - name: username
            value: "user"
          - name: password
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
        tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        restartPolicy: Never
  pollingInterval: 10             # Optional. Default: 30 seconds
  minReplicaCount: 0              # Optional. Default: 0
  maxReplicaCount: 8000           # Optional. Default: 100
  successfulJobsHistoryLimit: 5   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5       # Optional. Default: 100. How many failed jobs should be kept.
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://user:<mq_password>@rabbitmq.default.svc.cluster.local:5672
        queueName: sample
        mode: QueueLength
        value: "1"